### PR TITLE
Sidebar Toggling functionality is fixed

### PR DESCRIPTION
**Pull request by RameezMurtaza**
@jbampton @johnbampton Thanks for having to work on this issue #6

### CODE REVIEW

**Review by jbampton — CHANGES_REQUESTED** [review]
Please indent the CSS code correctly

**Comment by RameezMurtaza** [comment]
CSS indent Properly now !!!

**Comment by jbampton** [comment]
Just indent the CSS code you added not the whole file

**Comment by jbampton** [comment]
Seems the Cloudflare deploy preview did not run.  Not your fault.  

Perhaps since you used main branch instead of a feature branch ?

**Comment by RameezMurtaza** [comment]
yeah I used the main branch

**Comment by BaseMax** [comment]
Thanks, but it seems still there is a bug with the navigation/toggle button.

https://one-language.github.io/Document/?fff#/en/operators

Center of the button is not clickable:
image

But bottom side of the button is okay:

image

**Comment by BaseMax** [comment]
It seems my cursor is not visible in the above screenshots. anyway, you can understand it from my text. It seems the bug is not fixed totally.

**Comment by BaseMax** [comment]
I think the repository is live here: https://one-language.github.io/Document/?fff#/en/operators

**Pull request merged**
