### PR TITLE
docs: Translation to Turkish language.

### PR DESCRIPTION
**Pull request by uraninite**
Not finished but ~%70 completed.

### CODE REVIEW

**Comment by johnbampton** [comment]
All tests must pass before merging

**Comment by BaseMax** [comment]
Thanks, you are fluent in English?
What about your writing skills?

**Review by BaseMax — DISMISSED** [review]
Thanks, only need to run pre-commit.

**Comment by 0000x582d6976** [comment]
> Thanks, you are fluent in English?
> What about your writing skills?
@BaseMax 

Generally I'm using English for research. So, I'm reading and understanding the articles. I don't have experience about writing.

**Comment by jbampton** [comment]
Review time again everyone

**Review by BaseMax — APPROVED** [review]
Thanks, But if you want to do more contribute. please focus on English. since we need English at first.

**Pull request merged**
