### PR TITLE
convert some words to Farsi

### PR DESCRIPTION
**Pull request by PooiaFerdowsi**
انگلیسی اش رو نمی دونستم فارسی نوشتم.
I can't translate to English so write it Persian 

چند کلمه رو به فارسی برگردوندم . البته یکم ( یکم که نه خیلی ) تحت الفظی ترجمه اشون کردم .

این هم از بی کاری می نویسم .

Pronunciation :
chand kallamma ru/roo ba farsi bar gar doondam

### CODE REVIEW

**Review by jbampton — COMMENTED** [review]
Minor lint errors that I can fix next time around.

I say approve as long as @BaseMax thinks "text" is correct.

**Review by jbampton — COMMENTED** [review]
Can you please rebase or update your PR ?

**Comment by PooiaFerdowsi** [comment]
I've check was test was not success , and update pull request

**Comment by BaseMax** [comment]
Welcome Pooria, We need your help more of that. @PooiaFerdowsi

**Pull request merged**
